/* This file was generated by syncqt. */
#ifndef QT_QT3DCORE_VERSION_H
#define QT_QT3DCORE_VERSION_H

#define QT3DCORE_VERSION_STR "5.6.1"

#define QT3DCORE_VERSION 0x050601

#endif // QT_QT3DCORE_VERSION_H
