cd %~dp0%..\\appleseed-1.6.0-beta

mkdir sandbox\bin
mkdir sandbox\schemas

mkdir build
cd build
rm -f CMakeCache.txt

rem We need to have the lib dir
set BACKUP_PATH=%PATH%
set PATH=%PATH%;%BUILD_DIR%\\lib;%BUILD_DIR%\\bin

cmake -Wno-dev -G %CMAKE_GENERATOR% -DCMAKE_BUILD_TYPE=%BUILD_TYPE% -DPYTHON_LIBRARY=%BUILD_DIR%\lib -DPYTHON_INCLUDE_DIR=%BUILD_DIR%\include -DWITH_OSL=ON -DWITH_CLI=ON -DWITH_STUDIO=OFF -DWITH_TOOLS=OFF -DWITH_PYTHON=ON -DWITH_OSL=ON -DUSE_STATIC_BOOST=OFF -DUSE_STATIC_OIIO=OFF -DUSE_STATIC_EXR=OFF -DUSE_STATIC_OSL=OFF -DUSE_EXTERNAL_ZLIB=ON -DUSE_EXTERNAL_EXR=ON -DUSE_EXTERNAL_PNG=ON -DUSE_EXTERNAL_XERCES=ON -DUSE_EXTERNAL_OSL=ON -DUSE_EXTERNAL_OIIO=ON -DUSE_EXTERNAL_ALEMBIC=ON -DWARNINGS_AS_ERRORS=OFF -DUSE_SSE=ON -DCMAKE_PREFIX_PATH=%BUILD_DIR% -DCMAKE_INSTALL_PREFIX=%BUILD_DIR%\appleseed -DBOOST_ROOT=%BUILD_DIR% -DIMATH_INCLUDE_DIR=%BUILD_DIR%\\include -DIMATH_HALF_LIBRARY=%BUILD_DIR%\\lib\\Half.lib -DIMATH_IEX_LIBRARY=%BUILD_DIR%\\lib\\Iex-2_2.lib -DIMATH_MATH_LIBRARY=%BUILD_DIR%\\lib\\Imath-2_2.lib -DOPENEXR_INCLUDE_DIR=%BUILD_DIR%\\include -DOPENEXR_IMF_LIBRARY=%BUILD_DIR%\\lib\\IlmImf-2_2.lib -DOPENEXR_THREADS_LIBRARY=%BUILD_DIR%\\lib\\IlmThread-2_2.lib -DXERCES_LIBRARY=%BUILD_DIR%\\lib\\xerces-c_static_3.lib -DOSL_INCLUDE_DIR=%BUILD_DIR%\include OSL_EXEC_LIBRARY=%BUILD_DIR%\lib\oslexec.lib OSL_COMP_LIBRARY=%BUILD_DIR%\lib\oslcomp.lib OSL_QUERY_LIBRARY=%BUILD_DIR%\lib\oslquery.lib ..
cmake --build . --config %BUILD_TYPE% --target install

rem Restore path
set PATH=%BACKUP_PATH%

cd %ROOT_DIR%
