cd %~dp0%..\openvdb-4.0.2

mkdir %BUILD_DIR%\doc\licenses
copy openvdb\LICENSE %BUILD_DIR%\doc\licenses\openvdb

mkdir gafferBuild
cd gafferBuild

cmake -Wno-dev -G %CMAKE_GENERATOR% -DCMAKE_BUILD_TYPE=%BUILD_TYPE% -DCMAKE_INSTALL_PREFIX=%BUILD_DIR% -DOPENVDB_BUILD_UNITTESTS=OFF -DOPENVDB_BUILD_DOCS=OFF -DOPENVDB_BUILD_PYTHON_MODULE=OFF -DUSE_GLFW3=OFF -DTBB_LOCATION=%BUILD_DIR% -DBOOST_ROOT=%BUILD_DIR% -DGLEW_LOCATION=%BUILD_DIR% -DILMBASE_LOCATION=%BUILD_DIR% -DOPENEXR_LOCATION=%BUILD_DIR% -DBLOSC_LOCATION=%BUILD_DIR% ..
cmake --build . --config %BUILD_TYPE% --target install

cd %ROOT_DIR%
