SETLOCAL

set ARCHIVE_ROOT_NAME=alembic-%ALEMBIC_VERSION%
set WORKING_DIR=%ROOT_DIR%\%ARCHIVE_ROOT_NAME%

mkdir %WORKING_DIR%
copy %ARCHIVE_DIR%\%ARCHIVE_ROOT_NAME%.tar.gz %ROOT_DIR%

cd %ROOT_DIR%

%ROOT_DIR%\winbuild\7zip\7za.exe e -aoa %ARCHIVE_ROOT_NAME%.tar.gz
if %ERRORLEVEL% NEQ 0 (exit /b %ERRORLEVEL%)
%ROOT_DIR%\winbuild\7zip\7za.exe x -aoa %ARCHIVE_ROOT_NAME%.tar
if %ERRORLEVEL% NEQ 0 (exit /b %ERRORLEVEL%)

cd %WORKING_DIR%

mkdir %BUILD_DIR%\doc\licenses
copy LICENSE.txt %BUILD_DIR%\doc\licenses\alembic

mkdir gafferBuild
cd gafferBuild
del /f CMakeCache.txt

cmake -Wno-dev -G %CMAKE_GENERATOR% -DCMAKE_BUILD_TYPE=%BUILD_TYPE% -DCMAKE_INSTALL_PREFIX=%BUILD_DIR% -DCMAKE_PREFIX_PATH=%BUILD_DIR% -DALEMBIC_NO_TESTS=ON -DALEMBIC_NO_OPENGL=ON -DBoost_NO_SYSTEM_PATHS=ON -DBoost_NO_BOOST_CMAKE=ON -DBOOST_ROOT=%BUILD_DIR% -DHDF5_ROOT=%BUILD_DIR% -DILMBASE_ROOT=%BUILD_DIR% -DUSE_TESTS=OFF -DUSE_HDF5=ON -DUSE_PYILMBASE=OFF -DUSE_PYALEMBIC=OFF -DUSE_ARNOLD=OFF -DUSE_PRMAN=OFF -DUSE_MAYA=OFF -DALEMBIC_LIB_USES_BOOST=TRUE -DALEMBIC_ILMBASE_HALF_LIB=%BUILD_DIR%\lib\half.lib -DALEMBIC_ILMBASE_IEX_LIB=%BUILD_DIR%\lib\Iex-2_2.lib -DALEMBIC_ILMBASE_IEXMATH_LIB=%BUILD_DIR%\lib\IexMath-2_2.lib -DALEMBIC_ILMBASE_ILMTHREAD_LIB=%BUILD_DIR%\lib\IlmThread-2_2.lib -DALEMBIC_ILMBASE_IMATH_LIB=%BUILD_DIR%\lib\Imath-2_2.lib ..
if %ERRORLEVEL% NEQ 0 (exit /b %ERRORLEVEL%)
cmake --build . --config %BUILD_TYPE% --target install
if %ERRORLEVEL% NEQ 0 (exit /b %ERRORLEVEL%)

ENDLOCAL
