os:
  - linux
  - osx

language: c

compiler:
 - gcc
 - clang

env:
 - PY_VERSION=3.5.2
 - PY_VERSION=3.5.1
 - PY_VERSION=2.7.13
 - PY_VERSION=2.7.12
 - PY_VERSION=2.7.11
 - PY_VERSION=2.7.10
 - PY_VERSION=2.7.9
 - PY_VERSION=2.7.8
 - PY_VERSION=2.7.7
 - PY_VERSION=2.7.6
 - PY_VERSION=2.7.5
 - PY_VERSION=2.7.4
 - PY_VERSION=2.7.3

sudo: false

branches:
 only:
  - master
  - /^ci.*$/

addons:
  apt:
    packages:
     - libssl-dev

before_script:
 - wget -P /tmp/ https://raw.githubusercontent.com/davidsansome/python-cmake-buildsystem/dashboard/travis_dashboard.cmake

script:
 - ctest -V -S /tmp/travis_dashboard.cmake

after_script:
 - cat ${TRAVIS_BUILD_DIR}-build/CMakeCache.txt

